# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 11:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_historico', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('descricao', models.CharField(max_length=60)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
            ],
            options={
                'verbose_name': 'Histórico Padrão',
                'verbose_name_plural': 'Históricos Padrões',
            },
        ),
        migrations.DeleteModel(
            name='HistoricoPadrao',
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together=set([('codigo_historico', 'descricao')]),
        ),
    ]
