# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

import ctb.models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterField(
            model_name='historico',
            name='codigo_historico',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)],
                                                   verbose_name='Código do Histórico'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='codigo_participante',
            field=models.CharField(blank=True, default='', max_length=3, null=True,
                                   verbose_name='Código do Participante'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='data_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Documento'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='historico',
            field=models.TextField(max_length=200, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=10, null=True,
                                   verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='tipo_documento',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Tipo do Documento'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Informe valor positivo.', max_digits=16,
                                      max_length=16, validators=[ctb.models.validate_valor_minimo]),
        ),
    ]
