# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 18:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0002_auto_20170708_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['descricao'], 'verbose_name': 'Histórico Padrão', 'verbose_name_plural': 'Históricos Padrões'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='codigo_historico',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
