# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0002_auto_20171019_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='sigla',
            field=models.CharField(default='CH', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together=set([('sigla', 'descricao')]),
        ),
    ]
