# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0001_initial'),
        ('ctb', '0003_auto_20170710_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalEmpresa'),
        ),
    ]
