# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0009_globalcontareferencialbacen_globcontareferencialdinamica_globcontareferencialsusep'),
        ('ctb', '0004_historico_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.PositiveSmallIntegerField(unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição da Conta')),
                ('tipo_conta', models.CharField(choices=[('A', 'Analítica'), ('S', 'Sintética'), ('G', 'Grupo')], max_length=1, verbose_name='Tipo da Conta')),
                ('conta_ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('grau_conta', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Grau da Conta')),
                ('origem', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Origem da Conta')),
                ('natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza da Conta')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('conta_referencial_bacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_BACEN', to='glb.GlobalContaReferencialBacen')),
                ('conta_referencial_dinamica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_Dinamica', to='glb.GlobContaReferencialDinamica')),
                ('conta_referencial_susep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Referencial_Susep', to='glb.GlobContaReferencialSusep')),
                ('conta_saldo_balanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resultado', to='ctb.PlanoDeConta')),
                ('conta_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Superior', to='ctb.PlanoDeConta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalEmpresa')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo_conta'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='planodeconta',
            unique_together=set([('empresa', 'codigo_conta')]),
        ),
    ]
