# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 13:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0004_auto_20171019_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ctb.TipoDocumento'),
        ),
    ]
