# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0004_auto_20170902_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='codigo_conta',
            field=models.CharField(max_length=9, unique=True, verbose_name='Código da Conta'),
        ),
    ]
