# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0005_auto_20170722_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanoDeConta',
            new_name='Conta',
        ),
    ]
