# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0005_auto_20170904_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='codigo_conta',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Apenas valores numéricos são permitidos.')], verbose_name='Código da Conta'),
        ),
    ]
