# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 13:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0005_auto_20171019_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='codigo_participante',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ctb.Participante'),
        ),
    ]
