# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 12:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0006_auto_20170905_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competencia', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('B', 'Bloqueada pela Contabildade')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-data_competencia'],
            },
        ),
        migrations.AlterField(
            model_name='conta',
            name='codigo_conta',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Apenas valores numéricos, de 0 até 9, são permitidos.')], verbose_name='Código da Conta'),
        ),
    ]
