# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 21:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0007_auto_20171215_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_reduzido', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_reduzido', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Processo')),
            ],
            options={
                'verbose_name': 'Rotina',
                'verbose_name_plural': 'Rotinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_reduzido', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Rotina')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipomovimento',
            name='modulo',
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Modulo'),
        ),
        migrations.AddField(
            model_name='aba',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Rotina'),
        ),
    ]
