# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0007_auto_20170907_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='data_competencia',
            field=models.DateField(help_text='Digite no formato: DD/MM/YYYY', unique=True),
        ),
    ]
