# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctb', '0008_auto_20170907_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoContabilHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='CTB', max_length=3)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16, max_length=16)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16, max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='competencia',
            name='data_competencia',
            field=models.DateField(help_text='Digite no formato: dd/mm/aaaa', unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(default='MATRIZ', max_length=15, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='movimentocontabilheader',
            name='data_competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Competencia'),
        ),
        migrations.AddField(
            model_name='movimentocontabilheader',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
