# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0008_auto_20171219_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='modulo',
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
