# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 13:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0009_auto_20170911_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=16, max_length=16)),
                ('d_c', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('historico', models.TextField(max_length=200)),
                (
                    'codigo_historico',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Historico')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.Conta')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movimentocontabilheader',
            options={'ordering': ['-id'], 'verbose_name': 'Movimento Contábil',
                     'verbose_name_plural': 'Movimentos Contábeis'},
        ),
        migrations.AlterField(
            model_name='movimentocontabilheader',
            name='data_lancamento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentocontabil',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctb.MovimentoContabilHeader'),
        ),
    ]
