# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0010_auto_20170912_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovimentoContabil',
            new_name='LancamentoContabil',
        ),
        migrations.AlterModelOptions(
            name='lancamentocontabil',
            options={'ordering': ['id'], 'verbose_name': 'Lançamento Contábil',
                     'verbose_name_plural': 'Lançamentos Contábeis (Lançamentos)'},
        ),
        migrations.AlterModelOptions(
            name='movimentocontabilheader',
            options={'ordering': ['-id'], 'verbose_name': 'Movimento Contábil',
                     'verbose_name_plural': 'Movimentos Contábeis (Header)'},
        ),
    ]
