# Generated by Django 2.0 on 2017-12-30 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ctb', '0010_auto_20171220_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aba',
            name='rotina',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='rotina',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='rotina',
        ),
        migrations.RemoveField(
            model_name='tipomovimento',
            name='modulo',
        ),
        migrations.DeleteModel(
            name='Aba',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.DeleteModel(
            name='Processo',
        ),
        migrations.DeleteModel(
            name='Rotina',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
