# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glb', '0003_auto_20170714_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('apelido', models.CharField(default='', max_length=50, null=True)),
                ('endereco', models.CharField(default='Endereco', max_length=50)),
                ('complemento', models.CharField(default='', max_length=50, null=True)),
                ('cep', models.IntegerField(default=0, null=True)),
                ('bairro', models.CharField(default='Bairro', max_length=30)),
                ('cidade', models.CharField(default='Cidade', max_length=50)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('nivel_acesso', models.IntegerField(default=0)),
                ('supervisor', models.BooleanField(default=False)),
                ('segunda_feira', models.BooleanField(default=True)),
                ('terca_feira', models.BooleanField(default=True)),
                ('quarta_feira', models.BooleanField(default=True)),
                ('quinta_feira', models.BooleanField(default=True)),
                ('sexta_feira', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=True)),
                ('domnigo', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(default='8:00')),
                ('hora_final', models.TimeField(default='17:00')),
                ('opera_caixa', models.BooleanField(default=False)),
                ('numero_checkout', models.IntegerField(default=0, null=True)),
                ('comprador', models.BooleanField(default=False)),
                ('limite_por_compra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('limite_compra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('funcionario', models.CharField(default='', max_length=2, null=True)),
                ('vendedor', models.CharField(default='V', max_length=2)),
                ('codigo_supervisor', models.IntegerField(default=0, null=True)),
                ('comissao_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comissao_sobre_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('objetivo_mensal_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('banco_numero', models.IntegerField(default=0, null=True)),
                ('banco_agencia', models.IntegerField(default=0, null=True)),
                ('banco_digito_verficador', models.IntegerField(default=0, null=True)),
                ('data_nascimento', models.DateField(blank=True, default='', null=True)),
                ('regiao_venda', models.CharField(default='', max_length=13, null=True)),
                ('departamento', models.CharField(default='', max_length=15, null=True)),
                ('matricula', models.CharField(default='', max_length=20, null=True)),
                ('identidade', models.CharField(default='', max_length=20, null=True)),
                ('data_emissao', models.DateField(default='', null=True)),
                ('orgao_emissor', models.CharField(default='', max_length=10, null=True)),
                ('fisica_juridica', models.CharField(default='F', max_length=1)),
                ('cpf_cnpj', models.IntegerField(default=0, unique=True)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('ddd_residencia', models.IntegerField(default=0, null=True)),
                ('tel_residencia', models.IntegerField(default=0, null=True)),
                ('ddd_celular', models.IntegerField(default=0, null=True)),
                ('tel_celular', models.IntegerField(default=0, null=True)),
                ('informacoes_adicionais', models.TextField(default='', max_length=256, null=True)),
                ('email', models.EmailField(default='usuario@email.com', max_length=50)),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalEmpresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
