# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('nome',), 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf_cnpj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_emissao',
            field=models.DateField(default='2000-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, default='2000-12-31', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('cpf_cnpj', 'nome')]),
        ),
    ]
