# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170717_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([]),
        ),
    ]
