# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170717_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
