# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170717_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
