# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170717_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domingo_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domingo_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quarta_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quarta_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quinta_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quinta_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sabado_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sabado_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segunda_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segunda_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexta_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexta_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terca_hora_final',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terca_hora_inicio',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
    ]
