# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170718_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
