# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170718_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
