# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170718_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalCodigoEstado'),
        ),
    ]
