# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170718_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='funcionario',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Sim', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vendedor',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Não', max_length=3),
        ),
    ]
