# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170718_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regiao_venda',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Região de Venda'),
        ),
    ]
