# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170718_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data_emissao',
            field=models.DateField(blank=True, default='2000-12-31', null=True),
        ),
    ]
