# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170718_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uf',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalCodigoEstado'),
        ),
    ]
