# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 16:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('nome', models.CharField(max_length=100)),
                ('pago_ate', models.DateField()),
                ('em_teste', models.BooleanField(default=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalCodigoCnae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo_atividade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de Atividade')),
                ('simples_nacional', models.BooleanField(default=False, verbose_name='Simples Nacional')),
                ('anexo_simples_nacional', models.CharField(default='', max_length=3, verbose_name='AnexoSimples Nacional')),
                ('per_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Percentual de Imposto')),
                ('inscricao_estadual', models.BooleanField(default=False, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Código do CNAE',
                'verbose_name_plural': 'Códigos do CNAE',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GlobalCodigoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('estado', models.CharField(max_length=2)),
                ('data_inicial', models.DateField(default='2009-01-01', max_length=10)),
            ],
            options={
                'verbose_name': 'Estado Brasileiro',
                'verbose_name_plural': 'Estados Brasileiros',
                'ordering': ('estado',),
            },
        ),
        migrations.CreateModel(
            name='GlobalContaReferencialBacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, max_length=8, null=True, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(choices=[('A', 'Analítica'), ('S', 'Sintética')], max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.IntegerField(verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalContaReferencialBacen')),
            ],
            options={
                'verbose_name': 'Conta Referencial BACEN',
                'verbose_name_plural': 'Contas Referenciais BACEN',
                'ordering': ('codigo_conta',),
            },
        ),
        migrations.CreateModel(
            name='GlobalMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('descricao', models.CharField(max_length=256)),
                ('data_inicial', models.DateField(default='2009-01-01', max_length=8)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GlobalNaturezaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('grupo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Código de Natureza Jurídica',
                'verbose_name_plural': 'Códigos de Naturezas Jurídicas',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GlobContaReferencialDinamica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, max_length=8, null=True, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobContaReferencialDinamica')),
            ],
            options={
                'verbose_name': 'Conta Referencial Dinâmica BACEN',
                'verbose_name_plural': 'Contas Referenciais Dinâmicas BACEN',
                'ordering': ('codigo_conta',),
            },
        ),
        migrations.CreateModel(
            name='GlobContaReferencialSusep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(max_length=8, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.IntegerField(verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobContaReferencialSusep')),
            ],
            options={
                'verbose_name': 'Conta Referencial SUSEP',
                'verbose_name_plural': 'Contas Referenciais SUSEP',
                'ordering': ('codigo_conta',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='globalcodigocnae',
            unique_together=set([('codigo', 'descricao')]),
        ),
    ]
