# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCodigoCnae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo_atividade', models.CharField(max_length=80, verbose_name='Tipo de Atividade')),
                ('simples_nacional', models.BooleanField(default=False, verbose_name='Simples Nacional')),
                ('per_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Percentual de Imposto')),
                ('inscricao_estadual', models.BooleanField(default=False, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Código do CNAE',
                'verbose_name_plural': 'Códigos do CNAE',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GlobalCodigoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('estado', models.CharField(max_length=2)),
                ('data_inicial', models.DateField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
                'ordering': ('estado',),
            },
        ),
        migrations.CreateModel(
            name='GlobalEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='MATRIZ', max_length=15, verbose_name='Código')),
                ('razao_social', models.CharField(max_length=60, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=60, verbose_name='Nome Fantasia')),
                ('endereco', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='CEP')),
                ('telefone1', models.CharField(max_length=15, verbose_name='Telefone #1')),
                ('telefone2', models.CharField(max_length=15, verbose_name='Telefone #2')),
                ('data_processamento', models.DateField(max_length=8)),
                ('data_competencia', models.DateField(max_length=8)),
                ('site_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site da Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email da Empresa')),
                ('cnpj', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=15, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(max_length=15, verbose_name='Inscrição Municipal')),
                ('tipo_empresa', models.CharField(choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro presumido'), ('LR', 'Lucro Real')], default='LR', max_length=2)),
                ('agrupa_itens_pedido', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('bloqueia_clientes_em_atraso', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('codigo_cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalCodigoCnae')),
                ('contador_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to=settings.AUTH_USER_MODEL)),
                ('diretor_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalCodigoEstado')),
                ('gerente_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='GlobalMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('descricao', models.CharField(max_length=256)),
                ('data_inicial', models.DateField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Municípios',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GlobalNaturezaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('grupo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Códigos de Naturezas Jurídicas',
                'ordering': ('descricao',),
            },
        ),
        migrations.AddField(
            model_name='globalempresa',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalMunicipio'),
        ),
        migrations.AddField(
            model_name='globalempresa',
            name='natureza_juridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalNaturezaJuridica'),
        ),
    ]
