# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalempresa',
            name='codigo_cnae',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='contador_empresa',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='diretor_empresa',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='gerente_empresa',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='globalempresa',
            name='natureza_juridica',
        ),
        migrations.DeleteModel(
            name='GlobalEmpresa',
        ),
    ]
