# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0002_auto_20170714_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcodigocnae',
            name='tipo_atividade',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de Atividade'),
        ),
    ]
