# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0003_auto_20170714_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalmunicipio',
            options={'ordering': ('descricao',), 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='data_competencia',
            field=models.DateField(max_length=8, verbose_name='Data de Competência'),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='endereco',
            field=models.CharField(max_length=60, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='globalmunicipio',
            name='data_inicial',
            field=models.DateField(default='2009-01-01', max_length=8),
        ),
    ]
