# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0004_auto_20170717_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcodigoestado',
            options={'ordering': ('estado',), 'verbose_name': 'Estado Brasileiro', 'verbose_name_plural': 'Estados Brasileiros'},
        ),
        migrations.AlterModelOptions(
            name='globalnaturezajuridica',
            options={'ordering': ('descricao',), 'verbose_name': 'Código de Natureza Jurídica', 'verbose_name_plural': 'Códigos de Naturezas Jurídicas'},
        ),
        migrations.AlterField(
            model_name='globalcodigoestado',
            name='data_inicial',
            field=models.DateField(default='01/01/2009', max_length=10),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='contador_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='diretor_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='gerente_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='telefone1',
            field=models.CharField(default=0, max_length=15, verbose_name='Telefone #1'),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='telefone2',
            field=models.CharField(default=0, max_length=15, verbose_name='Telefone #2'),
        ),
    ]
