# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0005_auto_20170717_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalempresa',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
