# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0006_auto_20170717_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalempresa',
            name='contador_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='diretor_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalempresa',
            name='gerente_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
    ]
