# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0007_auto_20170717_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalempresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Inscrição Municipal'),
        ),
    ]
