# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0008_auto_20170717_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalContaReferencialBacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, max_length=8, null=True, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(choices=[('A', 'Analítica'), ('S', 'Sintética')], max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.IntegerField(verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glb.GlobalContaReferencialBacen')),
            ],
            options={
                'verbose_name': 'Conta Referencial BACEN',
                'verbose_name_plural': 'Contas Referenciais BACEN',
                'ordering': ('codigo_conta',),
            },
        ),
        migrations.CreateModel(
            name='GlobContaReferencialDinamica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, max_length=8, null=True, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobContaReferencialDinamica')),
            ],
            options={
                'verbose_name': 'Conta Referencial Dinâmica BACEN',
                'verbose_name_plural': 'Contas Referenciais Dinâmicas BACEN',
                'ordering': ('codigo_conta',),
            },
        ),
        migrations.CreateModel(
            name='GlobContaReferencialSusep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('data_inicio', models.DateField(max_length=8, verbose_name='Data de Início')),
                ('data_fim', models.DateField(max_length=8, verbose_name='Data Final')),
                ('tipo_conta', models.CharField(max_length=1, verbose_name='Tipo de Conta')),
                ('nivel_contabil', models.IntegerField(verbose_name='Nível Contábil')),
                ('codigo_natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Natureza')),
                ('utilizacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Utilização')),
                ('conta_superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glb.GlobContaReferencialSusep')),
            ],
            options={
                'verbose_name': 'Conta Referencial SUSEP',
                'verbose_name_plural': 'Contas Referenciais SUSEP',
                'ordering': ('codigo_conta',),
            },
        ),
    ]
