# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clientes', '0002_auto_20171012_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='schema_name',
            field=models.CharField(max_length=100),
        ),
    ]
